/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:85082c3d-5f64-4e53-92ef-ae73c3943d97",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_O6fU1YMEU",
    "aws_user_pools_web_client_id": "3otrbjpbh81r5k5ssuhijbga76",
    "oauth": {},
    "aws_content_delivery_bucket": "tree-20201001182022-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://tree-20201001182022-hostingbucket-prod.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;
